name: 'Build and push image to docker hub'

on: [push, pull_request]

env:
    DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
    DOCKER_USER: ${{ secrets.DOCKER_USER }}

jobs:
  build-push-image:
    runs-on: ubuntu-latest

    timeout-minutes: 2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push
        run: |
          echo "Building Docker image"
          pwd
          docker build -t $DOCKER_USER/hashdir:latest .
          docker login -u $DOCKER_USER -p $DOCKER_PAT
          docker push $DOCKER_USER/hashdir:latest

          echo "Image pushed successfully"
